title: Justyna's Pages
author: Justyna Walkowiak
email: justyna96walkowiak@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  My awsome notes.

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
